version: 2

sources:
  - name: public
    tables:
      - name: raw_online_retail

models: 
  - name: stg_online_retail
    description: >
      Standrdized column names, filters out null records, 
      casting columns to proper data types order the table by order_id

    columns:
      - name: customer_id
        tests:
          - not_null
      
      - name: order_id
        tests:
          - not_null

      - name: invoice_date
        description: "Datetime when the invoice was generated"
