models: 
  - name: dim_date_anchor
    description: > 
          date of a last purchase in the dataset to do reliable churn analysis,
          using this value instead of the date of today.

    columns:
      - name: snapshot_date
        description: "Most recent known invoice date across all transactions"
        tests:
          - not_null
  
  - name: date_customer_last_purchase
    description: >
      customer's most recent invoice date for each customer.
    columns:
      - name: customer_id
        description: "Customer identifier"
        tests: 
          - unique
          - not_null
      - name: last_order_date
        description: "Most recent invoice date for this customer"
        tests:
          - not_null

      
  - name: dim_customer
    description: >
      Customer details.
    columns: 
      - name: customer_id
        description: "Customer Identifier"
      - name: country
        description: "Country where the invoice created"
        tests:
          - not_null
      - name: order_id
        description: "Order Identifier"